# Default values for encryption-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry-vpc.cn-shanghai.aliyuncs.com/richemont/encryption-services
  tag: ((.Env.DOCKER_IMAGE_TAG))
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 750Mi
  requests:
    cpu: 100m
    memory: 500Mi

nodeSelector: {}

tolerations: []

affinity: {}

host_name: "apigw-ccp-quality-cn-shanghai.aliyun.rccad.net"
application_environment: "qual"
datacenter_type: "aliyun"
datacenter_location: "cn-east-2"

dd_agent_enabled: "false"

java_opts: "-Dccp.env=qual -Dspring.config.location=/configmaps/application.yml -Dspring.profiles.active=alibaba"

security:
  internal: "{bcrypt}$2a$10$sxU0q3AyCgJR7myQf4NZX.DwgAESAJgE4QyVm7MujOMlH.R/0vBeG"