# Default values for encryption
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 194341177395.dkr.ecr.us-east-1.amazonaws.com/encryptionservice
  tag: latest
  pullPolicy: IfNotPresent

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

service:
  type: ClusterIP
  port: 8080

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

java_opts: -Dspring.config.location=/opt/config/application.yml

security:
  encryptionKey: ""
