# Default values for encryption-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 117677030399.dkr.ecr.us-east-2.amazonaws.com/encryptionservice
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

nodeSelector: {}

tolerations: []

affinity: {}


java_opts: -Dspring.config.location=/opt/config/application.yml

security:
  encryptionKey: ""
spring:
  cloud:
    vault:
      token: 1111-2222-4444-5555