# Default values for encryption
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 117677030399.dkr.ecr.us-east-2.amazonaws.com/encryptionservice
  tag: latest
  pullPolicy: IfNotPresent


service:
  type: ClusterIP
  port: 8080

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

java_opts: -Dspring.config.location=/opt/config/application.yml

security:
  encryptionKey: ""
