apiVersion: v1
name: encryption-service
version: 1.0.0
appVersion: 1.0.0
description: Encryption Service Helm Chart
type: application
maintainers:
  - name: Jihed BEN YEDDER
    email: jiedbenyedder@gmail.com