version: v1
server:
  port: 8085
  servlet:
    context-path: /encryption
    application-display-name: encryption

security:
  encryptionKey: "testkey"

spring:
  cloud:
    vault:
      token: trztr
