version: v1
server:
  port: 8085
  servlet:
    context-path: /encryptionservice/${version}
    application-display-name: encryption-service

security:
  encryptionKey: "testkey"

management:
  health:
    solr:
      enabled=true:

spring:
  cloud:
    vault:
      profiles: dev
      scheme: http
      port: 1111
      host: 1.1.1.1
      authentication: token
      token: s3cr3t
