version: v1
server:
  port: 8085
  servlet:
    context-path: /encryptionservice/${version}
    application-display-name: encryption-service

security:
  encryptionKey: "testkey"


management:
  health:
    solr:
      enabled=true


spring:
  cloud:
    config: false
    vault:
      host: localhost
      uri: https://localhost:8200
      token: trztr
