version: v1
server:
  port: 8085
  servlet:
    context-path: /encryptionservice/${version}
    application-display-name: encryption-service

security:
  encryptionKey: "testkey"
spring:
  cloud:
    vault:
      token: 12234-45-454-454
