---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  labels:
    run: {{ include "encryption-services.name" .}}
data:
  application.yml: |
    version: v1
    server:
      port: 8080
      servlet:
        context-path: /encryptionservice/${version}
        application-display-name: encryptionservice
      undertow:
        worker-threads: {{ .Values.undertow_worker_threads | default 75 }}

    security:
      encryptionKey: {{ .Values.encryptionKey }}
    
    spring:
      cloud:
        vault:
          host: localhost
          config.lifecycle: 
            enabled: true
            min-renewal: 10s
            expiry-threshold: 30s
          kv.enabled: false
          uri: http://vault.vault:8200
          authentication: KUBERNETES
          kubernetes:
          role: encryption-app


