---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-role: "default"
  labels:
    run: {{ include "encryption-services.name" .}}
data:
  application.yml: |
    version: v1
    server:
      port: 8080
      servlet:
        context-path: /encryptionservice/${version}
        application-display-name: encryptionservice
      undertow:
        worker-threads: {{ .Values.undertow_worker_threads | default 75 }}

    security:
      encryptionKey: {{ .Values.encryptionKey }}
    
    spring.cloud.vault:
      host: localhost
      port: 8200
      scheme: http
      uri: http://vault.vault:8200
      authentication: KUBERNETES
      kubernetes:
        role: encryption-app


