---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap-file
  annotations:
    vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
    vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
    vault.security.banzaicloud.io/vault-role: "default"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data:
  application.yml: |
    version: v1
    server:
      port: 8080
      servlet:
        context-path: /encryption
        application-display-name: encryption

    security:
      encryptionKey: {{ .Values.encryptionKey }}
    
    management:
      endpoint:
        web:
          exposure:
            include: health
        health:
          enabled: true
          show-details: always
          probes:
            enabled: true
      health:
        readinessstate:
          enabled: true
        solr:
          enabled: false

    spring:
      cloud:
        config: false
        vault:
          host: localhost
          uri: https://vault.vault:8200
          authentication: TOKEN
          token: ${vault:secret/data/vault/token#VAULT_TOKEN}
          ssl:
            trust-store: file:/vault/jkscacert/ca.jks
            trust-store-password: changeit
          kubernetes:
            role: encryption-app


