apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "encryption-services.name" . }}
  annotations:
    checksum/config-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
    checksum/config-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
    #Kubernetes will notice that the pods have been updated and rollout new pods without downtime.
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: encrpytion-service
  template:
    metadata:
      labels:
        app: encrpytion-service
    spec:
      serviceAccountName: encryption-app
      volumes:
        - name: {{ .Release.Name }}-configmap-file
          configMap:
            name: {{ .Release.Name }}-configmap-file
        - name: vault-cacert
          secret:
            secretName: { { .Release.Name } }-vault-tls
        - name: vault-jks-cacert
          emptyDir: { }
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              port: 8080
              path: /encryptionservice/v1/actuator/health
            initialDelaySeconds: 50
            periodSeconds: 20
          readinessProbe:
            httpGet:
              port: 8080
              path: /encryptionservice/v1/actuator/health
            initialDelaySeconds: 50
            periodSeconds: 20
          volumeMounts:
            - name: {{ .Release.Name }}-configmap-file
              mountPath: /opt/config
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
