apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "encryption-services.name" . }}
  labels:
    app: {{ include "encryption-services.name" . }}
    chart: {{ include "encryption-services.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    environment: {{ .Values.application_environment }}
  annotations:
    checksum/config-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
    checksum/config-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "encryption-services.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "encryption-services.name" . }}
        release: {{ .Release.Name }}
        environment: {{ .Values.application_environment }}
    spec:
      volumes:
        - name: config
          configMap:
            name: "{{ .Release.Name }}-configmap-file"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /encryptionservice/v1/actuator/health
              port: http
            initialDelaySeconds: 80
          readinessProbe:
            httpGet:
              path: /encryptionservice/v1/actuator/health
              port: http
            initialDelaySeconds: 80
          volumeMounts:
            - name: config
              mountPath: /configmaps
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
