apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "encryption-services.name" . }}
  annotations:
    checksum/config-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
    checksum/config-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
    #Kubernetes will notice that the pods have been updated and rollout new pods without downtime.
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: encrpytion-service
  template:
    metadata:
      labels:
        app: encrpytion-service
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-jks
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - keytool
            - -importcert
            - -storepass
            - changeit
            - -noprompt
            - -file
            - /vault/cacert/ca.crt
            - -keystore
            - /vault/jkscacert/ca.jks
          volumeMounts:
            - mountPath: /vault/cacert
              name: vault-cacert
            - mountPath: /vault/jkscacert
              name: vault-jks-cacert
      serviceAccountName: encryption-app
      volumes:
        - name: vault-jks-cacert
          emptyDir: { }
        - name: vault-cacert
          secret:
            secretName: vault-tls

        - name: {{ .Release.Name }}-configmap-file
          configMap:
            name: {{ .Release.Name }}-configmap-file

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: VAULT_URI
              value: https://vault.vault:8200
            - name: VAULT_SSL_TRUST_STORE
              value: file:///vault/cacert/ca.jks
            - name: VAULT_SSL_TRUST_STORE_PASSWORD
              value: changeit
          livenessProbe:
            httpGet:
              port: http
              path: /encryptionservice/v1/actuator/health
            initialDelaySeconds: 50
          readinessProbe:
            httpGet:
              port: http
              path: /encryptionservice/v1/actuator/health
            initialDelaySeconds: 50
          # Mount the Secret holding the generated self-signed certificate for Vault
          # Create an ephemeral volume for holding the converted version of the ca.crt to jks
          volumeMounts:
            - name: {{ .Release.Name }}-configmap-file
              mountPath: /opt/config
            - name: vault-cacert
              mountPath: /vault/cacert
            - name: vault-jks-cacert
              mountPath: /vault/jkscacert

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
