apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "encryption-services.name" . }}
  labels:
    {{- include "encryption-services.labels" . | nindent 4 }}
  annotations:
    checksum/config-file: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
    checksum/config-env: {{ include (print $.Template.BasePath "/configmap-env.yaml") . | sha256sum }}
    #Kubernetes will notice that the pods have been updated and rollout new pods without downtime.
    timestamp: "{{ date "20060102150405" .Release.Time }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "encryption-services.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "encryption-services.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-configmap-file
          configMap:
            name: {{ .Release.Name }}-configmap-file
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /encryptionservice/v1/actuator/health
              port: http
            initialDelaySeconds: 80
          readinessProbe:
            httpGet:
              path: /encryptionservice/v1/actuator/health
              port: http
            initialDelaySeconds: 80
          volumeMounts:
            - name: {{ .Release.Name }}-configmap-file
              mountPath: /opt/config
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}
