apiVersion: v1
kind: Service
metadata:
  name: {{ include "encryption-service.name" . }}
  labels:
    run: {{ include "encryption-service.name" . }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app: {{ include "encryption-service.name" . }}
    release: {{ .Release.Name }}
