apiVersion: v1
kind: Service
metadata:
  name: {{ include "encryption.name" . }}
  labels:
    run: {{ include "encryption.name" .}}
  annotations:
 #   getambassador.io/config: |
  #    ---
  #    apiVersion: ambassador/v0
   #   kind:  Mapping
    #  name:  encryption_dev_mapping
     # prefix: /encryption/
      #service: encryption.default:8080
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "encryption.name" . }}
  selector:
    app: encryption
  
    
